// https://mediapipe-studio.webapps.google.com/demo/pose_landmarker?hl=pt-br

// 0  NOSE
// 1  LEFT_EYE_INNER
// 2  LEFT_EYE
// 3  LEFT_EYE_OUTER
// 4  RIGHT_EYE_INNER
// 5  RIGHT_EYE
// 6  RIGHT_EYE_OUTER
// 7  LEFT_EAR
// 8  RIGHT_EAR
// 9  MOUTH_LEFT
// 10 MOUTH_RIGHT

// 11 LEFT_SHOULDER
// 12 RIGHT_SHOULDER
// 13 LEFT_ELBOW
// 14 RIGHT_ELBOW
// 15 LEFT_WRIST
// 16 RIGHT_WRIST

// 17 LEFT_PINKY
// 18 RIGHT_PINKY
// 19 LEFT_INDEX
// 20 RIGHT_INDEX
// 21 LEFT_THUMB
// 22 RIGHT_THUMB

// 23 LEFT_HIP
// 24 RIGHT_HIP
// 25 LEFT_KNEE
// 26 RIGHT_KNEE
// 27 LEFT_ANKLE
// 28 RIGHT_ANKLE
// 29 LEFT_HEEL
// 30 RIGHT_HEEL
// 31 LEFT_FOOT_INDEX
// 32 RIGHT_FOOT_INDEX
