import { StyleSheet } from "react-native";
import { Colors, Fonts } from "../../../constants/theme";

const palette = Colors.dark;
const fontSans = Fonts.sans;
const fontMono = Fonts.mono;

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: palette.canvas,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderColor: palette.divider,
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  logoImg: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: palette.divider,
  },
  kicker: {
    color: palette.secondaryText,
    fontSize: 11,
    letterSpacing: 0.5,
    fontFamily: fontMono,
  },
  title: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0.3,
    fontFamily: fontSans,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    paddingVertical: 12,
    gap: 12,
  },
  heroRow: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  panel: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 16,
    padding: 14,
  },
  panelWide: {
    flex: 1,
    minWidth: 320,
    gap: 12,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  panelTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
    fontFamily: fontSans,
  },
  panelHint: {
    color: palette.secondaryText,
    fontSize: 12,
    fontFamily: fontSans,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.elevated,
  },
  statusText: {
    color: palette.text,
    fontSize: 12,
    fontFamily: fontSans,
  },
  timeline: {
    gap: 10,
  },
  timelineItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timelineMarker: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: palette.divider,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineMarkerText: {
    color: palette.text,
    fontWeight: "800",
    fontFamily: fontMono,
  },
  timelineText: {
    flex: 1,
    color: palette.secondaryText,
    fontSize: 13,
    fontFamily: fontSans,
    lineHeight: 18,
  },
  statsColumn: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    minWidth: 220,
  },
  statCard: {
    flex: 1,
    minWidth: 120,
    backgroundColor: "#0c0c0c",
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  statLabel: {
    color: palette.secondaryText,
    fontSize: 12,
    fontFamily: fontSans,
  },
  statValue: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: fontSans,
  },
  statHint: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: fontSans,
  },
  columns: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  panelStack: {
    flex: 1,
    minWidth: 300,
    gap: 12,
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.divider,
    backgroundColor: palette.canvas,
  },
  pillActive: {
    backgroundColor: palette.elevated,
    borderColor: palette.elevated,
  },
  pillText: {
    color: palette.secondaryText,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: fontSans,
  },
  pillTextActive: {
    color: palette.canvas,
  },
  dropzone: {
    borderWidth: 1,
    borderColor: palette.divider,
    borderStyle: "dashed",
    borderRadius: 14,
    padding: 14,
    backgroundColor: "#050505",
    gap: 6,
  },
  dropTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: fontSans,
  },
  dropSubtitle: {
    color: palette.secondaryText,
    fontSize: 12,
    fontFamily: fontSans,
  },
  referenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  referenceItem: {
    width: 86,
    height: 86,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.divider,
    position: "relative",
    backgroundColor: palette.canvas,
  },
  referenceThumb: {
    width: "100%",
    height: "100%",
  },
  removeBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(0,0,0,0.8)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.divider,
  },
  removeBadgeText: {
    color: palette.text,
    fontWeight: "800",
    fontSize: 12,
    fontFamily: fontSans,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: fontSans,
  },
  inputBlock: {
    gap: 6,
  },
  inputLabel: {
    color: palette.secondaryText,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: fontSans,
  },
  textArea: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 12,
    padding: 12,
    color: palette.text,
    backgroundColor: palette.canvas,
    fontFamily: fontSans,
  },
  textInput: {
    height: 46,
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 12,
    paddingHorizontal: 12,
    color: palette.text,
    backgroundColor: palette.canvas,
    fontFamily: fontSans,
  },
  hintRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ideaChip: {
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  ideaChipText: {
    color: palette.text,
    fontSize: 12,
    fontFamily: fontSans,
  },
  previewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  previewCard: {
    width: 260,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.divider,
    backgroundColor: palette.canvas,
  },
  previewImage: {
    width: "100%",
    height: 180,
  },
  previewMeta: {
    padding: 10,
    gap: 8,
  },
  previewCaption: {
    color: palette.text,
    fontSize: 13,
    fontFamily: fontSans,
  },
  previewActions: {
    flexDirection: "row",
    gap: 8,
  },
  primaryButton: {
    backgroundColor: palette.elevated || palette.text,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: palette.text,
    fontWeight: "800",
    fontFamily: fontSans,
  },
  ghostButton: {
    borderWidth: 1,
    borderColor: palette.divider,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: palette.surface,
  },
  ghostButtonText: {
    color: palette.text,
    fontWeight: "700",
    fontFamily: fontSans,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: palette.divider,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: palette.surface,
  },
  secondaryButtonText: {
    color: palette.text,
    fontWeight: "700",
    fontFamily: fontSans,
  },
});
